# SITE CONFIGURATION
baseurl: ""
url: "https://discgolfr.github.io"

# THEME-SPECIFIC CONFIGURATION
title: discgolfR                                 # site's title
description: "Data analysis, data science, and visualizations about disc golf using R"      # used by search engines
avatar: assets/img/dg_sfavicon.png                 # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: Disc golf data analysis using R  # Change Blog header text
header_feature_image: assets/img/feature-img/dg_basket_header.jpg
footer_text: >
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>
  <br>
  This site is supported by readers. <br> When you make purchases through the affiliate links you help fuel my little hobby. Thank you!

# Blog
excerpt: "truncate"                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics: "UA-186334656-1"                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: true                                   # To respect the usage of cookies
disqus_shortname:                                       # Your discus shortname for comments

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
